version: '3.8'
services:
    main:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8080:8000
        depends_on:
            - main_db
        networks:
            - travellist

    main_queue:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        depends_on:
            - main_db
        networks:
            - travellist

    main_db:
        image: mysql:5.7.22
        environment:
            MYSQL_DATABASE: main
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 33064:3306
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - travellist
        depends_on:
            - nginx


    nginx:
        image: nginx:alpine
        container_name: travellist-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - travellist

networks:
    travellist:
        driver: bridge
